server:
  port: 10000
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: https://example.org
        predicates:
        - Path=/red/{segment}